### ISSUE TITLE
What will I do with save.dat

### ISSUE THREAD

**Issue by ErneTalu** [Bt08s/GTSt4ler#1]
I got a save.dat but it doesnt has password so what can I do with save.dat. (I also tried to change it with mine but it didnt work)

**Comment by batuafk** [comment]
downlod ..._passwords.txt and try all of them

**Comment by ErneTalu** [comment]
save.dat is doesnt contains password anymore (Türkmüsün kanka. Save.dat içinde artık şifre falan yazmıyor ki)

**Comment by batuafk** [comment]
yazıyor sadece sen onu gt yoluna atınca gözükmüyor webhook ...passwords.txt gönderir pass varsa gerçekten

**Comment by ErneTalu** [comment]
Senin repostoryi bilmiyorum kendi save.dat stealerim ile save.dat ı aldım ben birinden. Fakat kendi growtopiamdaki dosyamla değişirsem işe yaramıyor çünkü yeni login sistemi ile artık ipye göre alıyor. Ayrıca içinde şifre falanda bulundurmuyor 100 den fazla kez bakmışımdır. Save.dat decoderim var onda bile boş dönüyor. (tankid_password_chk2 diyor sadece ve grow hesabı mail değil)
